<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/* @var Link $block */
use Romain\AdvancedWishList\Block\Menu\Link;
?>

<li class="link wishlist" id="advanced-wishlist-menu-item">
    <a id="advanced-wishlist-link" <?= /* @noEscape */ $block->getLinkAttributes() ?>>
        <?= $block->escapeHtml($block->getLabel()) ?>
        <span class="counter qty" style="display: none;">0</span>
    </a>
</li>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "advanced-wishlist": {
                        "component": "Romain_AdvancedWishList/js/view/advanced-wishlist"
                    }
                }
            }
        }
    }
</script>
